### ISSUE TITLE
is  watir-rspec2.3.0 gem can be used along  with Rspec 3.2 or later versions?

### ISSUE THREAD

**Issue by chandanaGollapudi** [watir/watir-rspec#14]
Hi,

I am using rspec3.2  along with watir-rspec2.3.0 to generate rspec html report along with attached screenshot link for failed test cases. Getting an error msg while spec execution. please find the attached error msg screenshot.

![errormsg](https://cloud.githubusercontent.com/assets/11437366/8594250/e3843b48-265c-11e5-8fa9-b0b530e5355d.png)

is  watir-rspec2.3.0 gem can be used along  with Rspec 3.2 ? could somebody help me in generating watir-rspec html report.

Thanks,
Chandana

**Comment by jarmo** [comment]
It should already work by default with RSpec 3. I don't know the rspec command line utility syntax from my mind, but if you follow the setup instructions in the [readme](https://github.com/watir/watir-rspec/blob/master/README.md) then you should be good to go without adding any special switches to the rspec, when running it.

**Comment by jarmo** [comment]
Reading also your e-mail I suspect the way you try to use `rspec` with custom formatters is wrong. See [here](https://www.relishapp.com/rspec/rspec-core/docs/command-line/format-option) and [here](https://www.relishapp.com/rspec/rspec-core/docs/formatters/custom-formatters) for more information.

You're probably using the RSpec 2.x syntax.

So, without trying it out myself, I guess you should use something like this instead:
`bundle exec rspec --require watir/rspec --format Watir::RSpec::HtmlFormatter --out output.html`

**Comment by jarmo** [comment]
Closing this due to long period (years) of inactivity.
