### ISSUE TITLE
Instantiate browser in before :suite?

### ISSUE THREAD

**Issue by Portalboy** [watir/watir-rspec#15]
In my program I am using Watir to spool up web browsers and test various pages for a website. The easiest way to do this (which I have been using) is to go with watir-rspec's default behavior of opening a new browser instance for every test package, then close it afterwards.

I really want to make my program more efficient, so that instead of opening and closing windows for every unit test, it will 'borrow' a browser that was already open from the previous test, redirect it to the page it tests on, and test. 
The problem with this is that although when I instantiate my browser object in before :all it works just fine, in before :suite it can't be accessed. If I puts the object name from before :all it comes back nil, and likewise within each spec file it comes back nil.

Basically, I'm instantiating the object in before :suite and destroying it in after :suite so that it can persist through all specs, then only close at the end. Is there anything I am missing about scope here? Is there a better way to do this altogether?
Furthermore, is there a way to do this while still maintaining the command shortening functionality 

(I.E. button(id: "foo") or send_keys :return)?

My spec_helper.rb

```ruby
require_relative '../login'
require_relative '../logInObject'

require 'watir'




# Configuration for watir-rspec
require "watir/rspec"

RSpec.configure do |config|
  # Use Watir::RSpec::HtmlFormatter to get links to the screenshots, html and
  # all other files created during the failing examples.
  config.add_formatter(:progress) if config.formatters.empty?
  config.add_formatter(Watir::RSpec::HtmlFormatter)

  # Open up the browser for each example.
#=begin
  config.before :all do
  
#  puts "----------before all!"
#    @browser = LoginDrone.new :internet_explorer if !@browser
#	@browser.doLogin
#	puts "Before all browser: #{@browser}"
#	sleep(3)
  end
  
  config.before :suite do
#  puts "----------before suite!"
#  puts "Before suite browser: #{@browser}"
	$user = Credentials.new #if !$user
	@browser = LoginDrone.new :internet_explorer if !@browser
	@browser.doLogin
	puts @browser
  end
  
#  config.before :all do
#	goto "office.rcsdev.com/dasqa"
#  end
#=end
=begin
  #This bit is of my own making, it chooses not to open a new browser if one exists.
  config.before :all do
    if @browser.nil?
		@browser = LoginDrone.new :internet_explorer
		doLogin
	end
  end
=end
#=begin
  # Close that browser after each example.
  config.after :suite do
  puts "----------after suite!" if @browser
  puts "after suite browser: #{@browser}"
    @browser.close if @browser
  end
#=end





  # Include RSpec::Helper into each of your example group for making it possible to
  # write in your examples instead of:
  #   @browser.goto "localhost"
  #   @browser.text_field(name: "first_name").set "Bob"
  #
  # like this:
  #   goto "localhost"
  #   text_field(name: "first_name").set "Bob"
  #
  # This needs that you've used @browser as an instance variable name in
  # before :all block.
  config.include Watir::RSpec::Helper

  # Include RSpec::Matchers into each of your example group for making it possible to
  # use #within with some of RSpec matchers for easier asynchronous testing:
  #   expect(@browser.text_field(name: "first_name")).to exist.within(2)
  #   expect(@browser.text_field(name: "first_name")).to be_present.within(2)
  #   expect(@browser.text_field(name: "first_name")).to be_visible.within(2)
  #
  # You can also use #during to test if something stays the same during the specified period:
  #   expect(@browser.text_field(name: "first_name")).to exist.during(2)
  config.include Watir::RSpec::Matchers
end

```

LoginDrone is an object that inherits from Watir::Browser with some added goodies, like the doLogin method which goes to my test site and gets a credential input.

P.S. I *-DON'T-* want to use global variables if at all possible, because A: they are inefficient and B: I want to eventually add multi-threading support.

**Comment by jarmo** [comment]
[watir-rspec](https://github.com/watir/watir-rspec) supports storing browser instance in an instance variable or a global variable for _command shortening functionality_ (via `#method_missing`). Reading your problem I'd suggest you to use a global variable.

I also noticed that you didn't want to use global variables and I agree that they might be misused in software development, but when used correctly then they do not cause any harm nor are they inefficient (can you elaborate what you meant by that in the first place?).

If you want to add multi-threading support in the future then you need to create multiple browsers or use multiple processess for running tests.

All in all, this would solve your problem for now (excluding multi-threading issue):
```ruby
before(:suite) { $browser = Watir::Browser.new }
after(:suite) { $browser.close }
```

**Comment by Portalboy** [comment]
I've always heard global variables are 'evil' because they use too much memory, generate namespace conflicts in larger programs and have numerous other issues. Here's a resource that describes what I'm talking about:
http://c2.com/cgi/wiki?GlobalVariablesAreBad

Additionally, if I'm using a global variable for the browser it makes multithreading hard. I'd like to be able to spin up a new browser instance at will, and that would require the use of local or instance variables.

Of course, this is all in due time. I appreciate your help, now I at least have a solution that will allow me to keep going until I can eventually figure out the multi-threading conundrum. Thank you!

I've closed the ticket because this solved my immediate issue. If you'd like to comment back with more, feel free, I'll keep watching the thread.

**Comment by jarmo** [comment]
As I mentioned in my previous reply then global variables are bad when misused (all these examples in your referred link are true). However, when used in places where it actually makes sense, they do not pose any threat. In this example, you have one browser instance, which is a singleton and can be stored in a global variable. No need to worry about namespace conflicts (no-one else should create another global `$browser` variable in your specs because there is no need and it does not make sense), about memory problems (because you still only have one variable which should not be garbage-collected) and so on.

The only problem you're referring to is multi-threading issue, but even for that it seems to me that you can use a global variable for storing different instances (unless you're going to use fresh browser instance for each spec). Or, even more likely, you're going to run a new Ruby process for each "thread", because Ruby in its essence is single threaded language (due to usage of GIL), which means that you can split up your specs and still re-use different global variables within each process - using instance variables would mean that you need to re-create browsers between each example group.

Do not be afraid of using global variables - just don't misuse them!

**Comment by Portalboy** [comment]
Ah, so if I run a new Ruby process, both processes can have global variables named the same thing and they won't conflict? If that's the case that is exactly what I wanted. Thank you!

**Comment by jarmo** [comment]
Yes, that's how global variables work.

I have not used it ever in production, but you might want to take a look [parallel_tests](https://github.com/grosser/parallel_tests) - maybe you can use it in your parallel tests endeavor.

**Comment by Portalboy** [comment]
Thank you, I will definitely take a look at that!
